In [ ]:
!unzip /content/turboaz.zip

Archive:  /content/turboaz.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /content/turboaz.zip or
        /content/turboaz.zip.zip, and cannot find /content/turboaz.zip.ZIP, period.

In [ ]:
import pandas as pd

df=pd.read_csv("/content/cars.csv")
df

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,...,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45158,f8691e2e-f153-423e-af27-77342fc9129b,/autos/8788210-chevrolet-cruze,2024-09-19 20:08:10.090329+00,Chevrolet Cruze,11000.0,AZN,"Bakı, dünən 11:56",bakı,19.09.2024,11:56,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,4,180 000 km,Ön,Bakı,aa61fec9-8ab7-441e-b1cd-48f7a9c338c3,/autos/8788210-chevrolet-cruze,ABS* Park radarı* Kondisioner
45159,9daabf69-a731-4d30-a6f5-1c7c7b74648c,/autos/8724162-mercedes-e-350-d,2024-09-19 20:08:10.090329+00,Mercedes E 350 d,23000.0,$,"Bakı, dünən 11:56",bakı,19.09.2024,11:56,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,310 000 km,Arxa,Bakı,c8ccedea-451a-41b0-95c5-3f3f3841b963,/autos/8724162-mercedes-e-350-d,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
45160,4d31f1d2-a71e-4349-b5b2-009aa47e91a9,/autos/8796594-bmw-320,2024-09-19 20:08:10.090329+00,BMW 320,14400.0,AZN,"Bakı, dünən 11:56",bakı,19.09.2024,11:56,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,380 000 km,Arxa,Bakı,f630a867-d06f-4799-9dd7-6cc96fad050a,/autos/8796594-bmw-320,Yüngül lehimli disklər* ABS* Yağış sensoru* Mə...
45161,2b8accab-9543-4103-ad4f-c271ac903828,/autos/8640669-chevrolet-lacetti,2024-09-19 20:08:10.090329+00,Chevrolet Lacetti,21500.0,AZN,"Bakı, dünən 11:56",bakı,19.09.2024,11:56,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,20 600 km,Ön,Bakı,eddf4153-b081-4ed4-b3cb-6628b717f22b,/autos/8640669-chevrolet-lacetti,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
45162,1e40d926-febd-42e7-9cca-4cd0f96a4d5c,/autos/8784513-mercedes-e-350,2024-09-19 20:08:10.090329+00,Mercedes E 350,32000.0,AZN,"Şirvan, dünən 11:56",şirvan,19.09.2024,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop(["id_x","car_rel_url_x","datetime_scrape","datetime_product","city","day","hour","Yerlərin sayı","Şəhər","car_rel_url","extra_info"],inplace=True,axis=1)

In [ ]:
df.head()

,name,price_x,currency_x,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,...,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yürüş,Ötürücü,car_details_id_y
0,Hyundai i30,15000.0,AZN,"2008, 1.6 L, 270 000 km",2008.0,1.6,L,270000.0,km,NaN,...,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,270 000 km,Ön,8d84d800-fafd-4d5c-b640-f47bd6c5ac20
1,LADA (VAZ) Niva Travel,23700.0,AZN,"2024, 1.7 L, 0 km",2024.0,1.7,L,0.0,km,NaN,...,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,0 km,Tam,2cf8b84b-adaf-467a-8f06-3dabcf866c8a
2,Toyota Land Cruiser,35600.0,$,"2011, 4.0 L, 164 750 km",2011.0,4.0,L,164750.0,km,NaN,...,4.0 L/282 a.g./Benzin,NaN,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,164 750 km,Tam,22bb3704-ebe7-4357-ba2f-1806d1a7042b
3,Hyundai Elantra,26700.0,AZN,"2018, 2.0 L, 126 000 km",2018.0,2.0,L,126000.0,km,NaN,...,2.0 L/150 a.g./Benzin,NaN,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,126 000 km,Ön,e0d16dac-4091-4417-916e-cadeff600f95
4,Toyota Prius,10500.0,AZN,"2007, 1.5 L, 354 000 km",2007.0,1.5,L,354000.0,km,NaN,...,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,354 000 km,Ön,82078856-0d07-4a0d-8123-69c2e5002e07

In [ ]:
df.drop(['car_details_id_y','Yürüş','Sahiblər','kilometrage_unit','attributes',],inplace=True,axis=1)

In [ ]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,barter,loan,salon,...,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,Hyundai i30,15000.0,AZN,2008.0,1.6,L,270000.0,NaN,NaN,NaN,...,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024.0,1.7,L,0.0,NaN,NaN,Salon,...,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,Toyota Land Cruiser,35600.0,$,2011.0,4.0,L,164750.0,NaN,NaN,NaN,...,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,Hyundai Elantra,26700.0,AZN,2018.0,2.0,L,126000.0,NaN,NaN,NaN,...,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,Toyota Prius,10500.0,AZN,2007.0,1.5,L,354000.0,NaN,NaN,NaN,...,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      45163 non-null  object
 1   price_x                   45163 non-null  float64
 2   currency_x                45163 non-null  object
 3   production_year           45162 non-null  float64
 4   engine_displacement_num   45162 non-null  float64
 5   engine_displacement_unit  45162 non-null  object
 6   kilometrage_num           45162 non-null  float64
 7   barter                    15532 non-null  object
 8   loan                      10888 non-null  object
 9   salon                     13016 non-null  object
 10  spare_parts               128 non-null    object
 11  vip                       19890 non-null  object
 12  featured                  10477 non-null  object
 13  img_url                   45162 non-null  object
 14  id_y                      45162 non-null  object
 15  cars_id                   45162 non-null  object
 16  car_rel_url_y             45162 non-null  object
 17  datetime                  45162 non-null  object
 18  description               44245 non-null  object
 19  price_y                   45162 non-null  float64
 20  currency_y                45162 non-null  object
 21  owner_name                31768 non-null  object
 22  shop_name                 13380 non-null  object
 23  phone                     45148 non-null  float64
 24  updated                   45162 non-null  object
 25  views                     45162 non-null  float64
 26  vin                       3215 non-null   object
 27  car_details_id_x          45162 non-null  object
 28  Ban növü                  45162 non-null  object
 29  Buraxılış ili             45162 non-null  float64
 30  Hansı bazar üçün yığılıb  32344 non-null  object
 31  Marka                     45162 non-null  object
 32  Model                     45162 non-null  object
 33  Mühərrik                  45162 non-null  object
 34  Qəzalı                    128 non-null    object
 35  Rəng                      45162 non-null  object
 36  Sürətlər qutusu           45162 non-null  object
 37  Vəziyyəti                 45161 non-null  object
 38  Yeni                      45162 non-null  object
 39  Ötürücü                   45162 non-null  object
dtypes: float64(8), object(32)
memory usage: 13.8+ MB

In [ ]:
df.drop(['phone','owner_name','cars_id','id_y','vin','description','datetime','car_rel_url_y'],inplace=True,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      45163 non-null  object
 1   price_x                   45163 non-null  float64
 2   currency_x                45163 non-null  object
 3   production_year           45162 non-null  float64
 4   engine_displacement_num   45162 non-null  float64
 5   engine_displacement_unit  45162 non-null  object
 6   kilometrage_num           45162 non-null  float64
 7   barter                    15532 non-null  object
 8   loan                      10888 non-null  object
 9   salon                     13016 non-null  object
 10  spare_parts               128 non-null    object
 11  vip                       19890 non-null  object
 12  featured                  10477 non-null  object
 13  img_url                   45162 non-null  object
 14  price_y                   45162 non-null  float64
 15  currency_y                45162 non-null  object
 16  shop_name                 13380 non-null  object
 17  updated                   45162 non-null  object
 18  views                     45162 non-null  float64
 19  car_details_id_x          45162 non-null  object
 20  Ban növü                  45162 non-null  object
 21  Buraxılış ili             45162 non-null  float64
 22  Hansı bazar üçün yığılıb  32344 non-null  object
 23  Marka                     45162 non-null  object
 24  Model                     45162 non-null  object
 25  Mühərrik                  45162 non-null  object
 26  Qəzalı                    128 non-null    object
 27  Rəng                      45162 non-null  object
 28  Sürətlər qutusu           45162 non-null  object
 29  Vəziyyəti                 45161 non-null  object
 30  Yeni                      45162 non-null  object
 31  Ötürücü                   45162 non-null  object
dtypes: float64(7), object(25)
memory usage: 11.0+ MB

In [ ]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,barter,loan,salon,...,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,Hyundai i30,15000.0,AZN,2008.0,1.6,L,270000.0,NaN,NaN,NaN,...,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024.0,1.7,L,0.0,NaN,NaN,Salon,...,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,Toyota Land Cruiser,35600.0,$,2011.0,4.0,L,164750.0,NaN,NaN,NaN,...,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,Hyundai Elantra,26700.0,AZN,2018.0,2.0,L,126000.0,NaN,NaN,NaN,...,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,Toyota Prius,10500.0,AZN,2007.0,1.5,L,354000.0,NaN,NaN,NaN,...,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön

In [ ]:
df.drop(['barter','loan','car_details_id_x','shop_name','views'],inplace=True,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      45163 non-null  object
 1   price_x                   45163 non-null  float64
 2   currency_x                45163 non-null  object
 3   production_year           45162 non-null  float64
 4   engine_displacement_num   45162 non-null  float64
 5   engine_displacement_unit  45162 non-null  object
 6   kilometrage_num           45162 non-null  float64
 7   salon                     13016 non-null  object
 8   spare_parts               128 non-null    object
 9   vip                       19890 non-null  object
 10  featured                  10477 non-null  object
 11  img_url                   45162 non-null  object
 12  price_y                   45162 non-null  float64
 13  currency_y                45162 non-null  object
 14  updated                   45162 non-null  object
 15  Ban növü                  45162 non-null  object
 16  Buraxılış ili             45162 non-null  float64
 17  Hansı bazar üçün yığılıb  32344 non-null  object
 18  Marka                     45162 non-null  object
 19  Model                     45162 non-null  object
 20  Mühərrik                  45162 non-null  object
 21  Qəzalı                    128 non-null    object
 22  Rəng                      45162 non-null  object
 23  Sürətlər qutusu           45162 non-null  object
 24  Vəziyyəti                 45161 non-null  object
 25  Yeni                      45162 non-null  object
 26  Ötürücü                   45162 non-null  object
dtypes: float64(6), object(21)
memory usage: 9.3+ MB

In [ ]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,salon,spare_parts,vip,...,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,Hyundai i30,15000.0,AZN,2008.0,1.6,L,270000.0,NaN,NaN,NaN,...,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024.0,1.7,L,0.0,Salon,NaN,vipped-icon,...,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,Toyota Land Cruiser,35600.0,$,2011.0,4.0,L,164750.0,NaN,NaN,vipped-icon,...,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,Hyundai Elantra,26700.0,AZN,2018.0,2.0,L,126000.0,NaN,NaN,vipped-icon,...,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,Toyota Prius,10500.0,AZN,2007.0,1.5,L,354000.0,NaN,NaN,vipped-icon,...,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön

In [ ]:
df.drop(['vip','Hansı bazar üçün yığılıb','spare_parts','salon'],inplace=True,axis=1)

In [ ]:
df.head()

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,featured,img_url,price_y,...,Buraxılış ili,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,Hyundai i30,15000.0,AZN,2008.0,1.6,L,270000.0,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,15000.0,...,2008.0,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024.0,1.7,L,0.0,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,23700.0,...,2024.0,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,Toyota Land Cruiser,35600.0,$,2011.0,4.0,L,164750.0,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,35600.0,...,2011.0,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,Hyundai Elantra,26700.0,AZN,2018.0,2.0,L,126000.0,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,26700.0,...,2018.0,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,Toyota Prius,10500.0,AZN,2007.0,1.5,L,354000.0,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,10500.0,...,2007.0,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön

In [ ]:
df.drop(['price_y'],inplace=True,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      45163 non-null  object
 1   price_x                   45163 non-null  float64
 2   currency_x                45163 non-null  object
 3   production_year           45162 non-null  float64
 4   engine_displacement_num   45162 non-null  float64
 5   engine_displacement_unit  45162 non-null  object
 6   kilometrage_num           45162 non-null  float64
 7   featured                  10477 non-null  object
 8   img_url                   45162 non-null  object
 9   currency_y                45162 non-null  object
 10  updated                   45162 non-null  object
 11  Ban növü                  45162 non-null  object
 12  Buraxılış ili             45162 non-null  float64
 13  Marka                     45162 non-null  object
 14  Model                     45162 non-null  object
 15  Mühərrik                  45162 non-null  object
 16  Qəzalı                    128 non-null    object
 17  Rəng                      45162 non-null  object
 18  Sürətlər qutusu           45162 non-null  object
 19  Vəziyyəti                 45161 non-null  object
 20  Yeni                      45162 non-null  object
 21  Ötürücü                   45162 non-null  object
dtypes: float64(5), object(17)
memory usage: 7.6+ MB

In [ ]:
df.drop(['img_url','featured','currency_y'],inplace=True,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      45163 non-null  object
 1   price_x                   45163 non-null  float64
 2   currency_x                45163 non-null  object
 3   production_year           45162 non-null  float64
 4   engine_displacement_num   45162 non-null  float64
 5   engine_displacement_unit  45162 non-null  object
 6   kilometrage_num           45162 non-null  float64
 7   updated                   45162 non-null  object
 8   Ban növü                  45162 non-null  object
 9   Buraxılış ili             45162 non-null  float64
 10  Marka                     45162 non-null  object
 11  Model                     45162 non-null  object
 12  Mühərrik                  45162 non-null  object
 13  Qəzalı                    128 non-null    object
 14  Rəng                      45162 non-null  object
 15  Sürətlər qutusu           45162 non-null  object
 16  Vəziyyəti                 45161 non-null  object
 17  Yeni                      45162 non-null  object
 18  Ötürücü                   45162 non-null  object
dtypes: float64(5), object(14)
memory usage: 6.5+ MB

In [ ]:
df

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,updated,Ban növü,Buraxılış ili,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,Hyundai i30,15000.0,AZN,2008.0,1.6,L,270000.0,13.09.2024,"Hetçbek, 5 qapı",2008.0,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,LADA (VAZ) Niva Travel,23700.0,AZN,2024.0,1.7,L,0.0,13.09.2024,"Offroader / SUV, 5 qapı",2024.0,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,Toyota Land Cruiser,35600.0,$,2011.0,4.0,L,164750.0,13.09.2024,"Offroader / SUV, 5 qapı",2011.0,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,Hyundai Elantra,26700.0,AZN,2018.0,2.0,L,126000.0,13.09.2024,Sedan,2018.0,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,Toyota Prius,10500.0,AZN,2007.0,1.5,L,354000.0,13.09.2024,Liftbek,2007.0,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45158,Chevrolet Cruze,11000.0,AZN,2012.0,1.6,L,180000.0,19.09.2024,"Hetçbek, 5 qapı",2012.0,Chevrolet,Cruze,1.6 L/109 a.g./Benzin,NaN,Ağ,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45159,Mercedes E 350 d,23000.0,$,2010.0,3.0,L,310000.0,19.09.2024,Sedan,2010.0,Mercedes,E 350 d,3.0 L/265 a.g./Dizel,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45160,BMW 320,14400.0,AZN,2005.0,2.0,L,380000.0,19.09.2024,Sedan,2005.0,BMW,320,2.0 L/177 a.g./Dizel,NaN,Qara,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45161,Chevrolet Lacetti,21500.0,AZN,2022.0,1.5,L,20600.0,19.09.2024,Sedan,2022.0,Chevrolet,Lacetti,1.5 L/107 a.g./Benzin,NaN,Gümüşü,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45162,Mercedes E 350,32000.0,AZN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[(df['name']=='Hyundai Santa Fe') & (df['price_x']==26500) & (df['Rəng']=='Qara')]

,name,price_x,currency_x,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,updated,Ban növü,Buraxılış ili,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
3272,Hyundai Santa Fe,26500.0,AZN,2013.0,2.0,L,102000.0,13.09.2024,"Offroader / SUV, 5 qapı",2013.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3735,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,13.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
10746,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,14.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
17818,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,15.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
24742,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,16.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
29040,Hyundai Santa Fe,26500.0,AZN,2013.0,2.0,L,102000.0,17.09.2024,"Offroader / SUV, 5 qapı",2013.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
31046,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,17.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
37822,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,18.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
43929,Hyundai Santa Fe,26500.0,AZN,2012.0,2.0,L,145000.0,19.09.2024,"Offroader / SUV, 5 qapı",2012.0,Hyundai,Santa Fe,2.0 L/265 a.g./Benzin,NaN,Qara,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön

In [ ]:
df.drop(['updated','name','engine_displacement_unit'],inplace=True,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   price_x                  45163 non-null  float64
 1   currency_x               45163 non-null  object
 2   production_year          45162 non-null  float64
 3   engine_displacement_num  45162 non-null  float64
 4   kilometrage_num          45162 non-null  float64
 5   Ban növü                 45162 non-null  object
 6   Buraxılış ili            45162 non-null  float64
 7   Marka                    45162 non-null  object
 8   Model                    45162 non-null  object
 9   Mühərrik                 45162 non-null  object
 10  Qəzalı                   128 non-null    object
 11  Rəng                     45162 non-null  object
 12  Sürətlər qutusu          45162 non-null  object
 13  Vəziyyəti                45161 non-null  object
 14  Yeni                     45162 non-null  object
 15  Ötürücü                  45162 non-null  object
dtypes: float64(5), object(11)
memory usage: 5.5+ MB

In [ ]:
df

,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Buraxılış ili,Marka,Model,Mühərrik,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,15000.0,AZN,2008.0,1.6,270000.0,"Hetçbek, 5 qapı",2008.0,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,23700.0,AZN,2024.0,1.7,0.0,"Offroader / SUV, 5 qapı",2024.0,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,35600.0,$,2011.0,4.0,164750.0,"Offroader / SUV, 5 qapı",2011.0,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,26700.0,AZN,2018.0,2.0,126000.0,Sedan,2018.0,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,10500.0,AZN,2007.0,1.5,354000.0,Liftbek,2007.0,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45158,11000.0,AZN,2012.0,1.6,180000.0,"Hetçbek, 5 qapı",2012.0,Chevrolet,Cruze,1.6 L/109 a.g./Benzin,NaN,Ağ,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45159,23000.0,$,2010.0,3.0,310000.0,Sedan,2010.0,Mercedes,E 350 d,3.0 L/265 a.g./Dizel,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45160,14400.0,AZN,2005.0,2.0,380000.0,Sedan,2005.0,BMW,320,2.0 L/177 a.g./Dizel,NaN,Qara,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45161,21500.0,AZN,2022.0,1.5,20600.0,Sedan,2022.0,Chevrolet,Lacetti,1.5 L/107 a.g./Benzin,NaN,Gümüşü,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45162,32000.0,AZN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop(['Buraxılış ili','Mühərrik'],inplace=True,axis=1)

In [ ]:
df_copy=df.copy()

In [ ]:
usd_to_azn = 1.7
df_copy.loc[df_copy["currency_x"] == "$", "price_x"] *= usd_to_azn
df_copy.loc[df_copy["currency_x"] == "$", "currency_x"] = "AZN"

In [ ]:
df_copy

,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Marka,Model,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,15000.0,AZN,2008.0,1.6,270000.0,"Hetçbek, 5 qapı",Hyundai,i30,NaN,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,23700.0,AZN,2024.0,1.7,0.0,"Offroader / SUV, 5 qapı",LADA (VAZ),Niva Travel,NaN,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,60520.0,AZN,2011.0,4.0,164750.0,"Offroader / SUV, 5 qapı",Toyota,Land Cruiser,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,26700.0,AZN,2018.0,2.0,126000.0,Sedan,Hyundai,Elantra,NaN,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,10500.0,AZN,2007.0,1.5,354000.0,Liftbek,Toyota,Prius,NaN,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45158,11000.0,AZN,2012.0,1.6,180000.0,"Hetçbek, 5 qapı",Chevrolet,Cruze,NaN,Ağ,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45159,39100.0,AZN,2010.0,3.0,310000.0,Sedan,Mercedes,E 350 d,NaN,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45160,14400.0,AZN,2005.0,2.0,380000.0,Sedan,BMW,320,NaN,Qara,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45161,21500.0,AZN,2022.0,1.5,20600.0,Sedan,Chevrolet,Lacetti,NaN,Gümüşü,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45162,32000.0,AZN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_copy['Qəzalı'].fillna(0,inplace=True)

<ipython-input-43-1cbcf968b15c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['Qəzalı'].fillna(0,inplace=True)

In [ ]:
df_copy

,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Marka,Model,Qəzalı,Rəng,Sürətlər qutusu,Vəziyyəti,Yeni,Ötürücü
0,15000.0,AZN,2008.0,1.6,270000.0,"Hetçbek, 5 qapı",Hyundai,i30,0,Gümüşü,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
1,23700.0,AZN,2024.0,1.7,0.0,"Offroader / SUV, 5 qapı",LADA (VAZ),Niva Travel,0,Yaşıl,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,Tam
2,60520.0,AZN,2011.0,4.0,164750.0,"Offroader / SUV, 5 qapı",Toyota,Land Cruiser,0,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Tam
3,26700.0,AZN,2018.0,2.0,126000.0,Sedan,Hyundai,Elantra,0,Boz,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
4,10500.0,AZN,2007.0,1.5,354000.0,Liftbek,Toyota,Prius,0,Qırmızı,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45158,11000.0,AZN,2012.0,1.6,180000.0,"Hetçbek, 5 qapı",Chevrolet,Cruze,0,Ağ,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45159,39100.0,AZN,2010.0,3.0,310000.0,Sedan,Mercedes,E 350 d,0,Ağ,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45160,14400.0,AZN,2005.0,2.0,380000.0,Sedan,BMW,320,0,Qara,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,Arxa
45161,21500.0,AZN,2022.0,1.5,20600.0,Sedan,Chevrolet,Lacetti,0,Gümüşü,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,Ön
45162,32000.0,AZN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45163 entries, 0 to 45162
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   price_x                  45163 non-null  float64
 1   currency_x               45163 non-null  object
 2   production_year          45162 non-null  float64
 3   engine_displacement_num  45162 non-null  float64
 4   kilometrage_num          45162 non-null  float64
 5   Ban növü                 45162 non-null  object
 6   Marka                    45162 non-null  object
 7   Model                    45162 non-null  object
 8   Qəzalı                   45163 non-null  object
 9   Rəng                     45162 non-null  object
 10  Sürətlər qutusu          45162 non-null  object
 11  Vəziyyəti                45161 non-null  object
 12  Yeni                     45162 non-null  object
 13  Ötürücü                  45162 non-null  object
dtypes: float64(4), object(10)
memory usage: 4.8+ MB

In [ ]:
df_copy.drop(['Vəziyyəti'],inplace=True,axis=1)

In [ ]:
df_copy.dropna(subset=['Model'],inplace=True)

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45162 entries, 0 to 45161
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   price_x                  45162 non-null  float64
 1   currency_x               45162 non-null  object
 2   production_year          45162 non-null  float64
 3   engine_displacement_num  45162 non-null  float64
 4   kilometrage_num          45162 non-null  float64
 5   Ban növü                 45162 non-null  object
 6   Marka                    45162 non-null  object
 7   Model                    45162 non-null  object
 8   Qəzalı                   45162 non-null  object
 9   Rəng                     45162 non-null  object
 10  Sürətlər qutusu          45162 non-null  object
 11  Yeni                     45162 non-null  object
 12  Ötürücü                  45162 non-null  object
dtypes: float64(4), object(9)
memory usage: 4.8+ MB

In [ ]:
df_copy

,price_x,currency_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Marka,Model,Qəzalı,Rəng,Sürətlər qutusu,Yeni,Ötürücü
0,15000.0,AZN,2008.0,1.6,270000.0,"Hetçbek, 5 qapı",Hyundai,i30,0,Gümüşü,Mexaniki,Xeyr,Ön
1,23700.0,AZN,2024.0,1.7,0.0,"Offroader / SUV, 5 qapı",LADA (VAZ),Niva Travel,0,Yaşıl,Mexaniki,Bəli,Tam
2,60520.0,AZN,2011.0,4.0,164750.0,"Offroader / SUV, 5 qapı",Toyota,Land Cruiser,0,Ağ,Avtomat,Xeyr,Tam
3,26700.0,AZN,2018.0,2.0,126000.0,Sedan,Hyundai,Elantra,0,Boz,Avtomat,Xeyr,Ön
4,10500.0,AZN,2007.0,1.5,354000.0,Liftbek,Toyota,Prius,0,Qırmızı,Variator,Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45157,28800.0,AZN,2017.0,1.6,151500.0,"Offroader / SUV, 5 qapı",Mini,Countryman,0,Göy,Avtomat,Xeyr,Ön
45158,11000.0,AZN,2012.0,1.6,180000.0,"Hetçbek, 5 qapı",Chevrolet,Cruze,0,Ağ,Mexaniki,Xeyr,Ön
45159,39100.0,AZN,2010.0,3.0,310000.0,Sedan,Mercedes,E 350 d,0,Ağ,Avtomat,Xeyr,Arxa
45160,14400.0,AZN,2005.0,2.0,380000.0,Sedan,BMW,320,0,Qara,Mexaniki,Xeyr,Arxa
45161,21500.0,AZN,2022.0,1.5,20600.0,Sedan,Chevrolet,Lacetti,0,Gümüşü,Avtomat,Xeyr,Ön

In [ ]:
df_copy.drop(['currency_x'],inplace=True,axis=1)

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45162 entries, 0 to 45161
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   price_x                  45162 non-null  float64
 1   production_year          45162 non-null  float64
 2   engine_displacement_num  45162 non-null  float64
 3   kilometrage_num          45162 non-null  float64
 4   Ban növü                 45162 non-null  object
 5   Marka                    45162 non-null  object
 6   Model                    45162 non-null  object
 7   Qəzalı                   45162 non-null  object
 8   Rəng                     45162 non-null  object
 9   Sürətlər qutusu          45162 non-null  object
 10  Yeni                     45162 non-null  object
 11  Ötürücü                  45162 non-null  object
dtypes: float64(4), object(8)
memory usage: 4.5+ MB

In [ ]:
df_copy

,price_x,production_year,engine_displacement_num,kilometrage_num,Ban növü,Marka,Model,Qəzalı,Rəng,Sürətlər qutusu,Yeni,Ötürücü
0,15000.0,2008.0,1.6,270000.0,"Hetçbek, 5 qapı",Hyundai,i30,0,Gümüşü,Mexaniki,Xeyr,Ön
1,23700.0,2024.0,1.7,0.0,"Offroader / SUV, 5 qapı",LADA (VAZ),Niva Travel,0,Yaşıl,Mexaniki,Bəli,Tam
2,60520.0,2011.0,4.0,164750.0,"Offroader / SUV, 5 qapı",Toyota,Land Cruiser,0,Ağ,Avtomat,Xeyr,Tam
3,26700.0,2018.0,2.0,126000.0,Sedan,Hyundai,Elantra,0,Boz,Avtomat,Xeyr,Ön
4,10500.0,2007.0,1.5,354000.0,Liftbek,Toyota,Prius,0,Qırmızı,Variator,Xeyr,Ön
...,...,...,...,...,...,...,...,...,...,...,...,...
45157,28800.0,2017.0,1.6,151500.0,"Offroader / SUV, 5 qapı",Mini,Countryman,0,Göy,Avtomat,Xeyr,Ön
45158,11000.0,2012.0,1.6,180000.0,"Hetçbek, 5 qapı",Chevrolet,Cruze,0,Ağ,Mexaniki,Xeyr,Ön
45159,39100.0,2010.0,3.0,310000.0,Sedan,Mercedes,E 350 d,0,Ağ,Avtomat,Xeyr,Arxa
45160,14400.0,2005.0,2.0,380000.0,Sedan,BMW,320,0,Qara,Mexaniki,Xeyr,Arxa
45161,21500.0,2022.0,1.5,20600.0,Sedan,Chevrolet,Lacetti,0,Gümüşü,Avtomat,Xeyr,Ön

In [ ]:
df_copy.drop(['Qəzalı'],inplace=True,axis=1)

In [ ]:
df_copy = df_copy.sample(frac=0.1, random_state=42)

In [ ]:
X=df_copy.drop('price_x',axis=1)
y=df_copy['price_x'].copy()

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
import numpy as np
cars_num=X_train.select_dtypes(include=[np.number]).columns
cars_cat=X_train.select_dtypes(exclude=[np.number]).columns

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

cat_pipeline=Pipeline([
    ('one_hot',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

num_pipeline=Pipeline([
    ('scale',StandardScaler())
])

In [ ]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer([
    ('num',num_pipeline,cars_num),
    ('cat',cat_pipeline,cars_cat)
],remainder='passthrough')

In [ ]:
from sklearn.tree import DecisionTreeRegressor
estimator = DecisionTreeRegressor(random_state=42)
full_pipeline=Pipeline([
    ('preprocessing',transformer),
    ('estimator',estimator)
])

In [ ]:
full_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  Index(['production_year', 'engine_displacement_num', 'kilometrage_num'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('one_hot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['Ban növü', 'Marka', 'Model', 'Rəng', 'Sürətlər qutusu', 'Yeni',
       'Ötürücü'],
      dtype='object'))])),
                ('estimator', DecisionTreeRegressor(random_state=42))])

In [ ]:
full_pipeline.score(X_test,y_test)

0.9052053193771528

In [ ]:
full_pipeline.score(X_train,y_train)

0.9957494921716015

In [ ]:
cars_predictions=full_pipeline.predict(X_test)
cars_predictions[:10]

array([ 50900.,  74120.,  11900.,  42000.,  14000., 114750.,  33490.,
        13200.,  14200.,  32500.])

In [ ]:
y_test[:10]

37983     50900.0
19371     75820.0
39965     10999.0
3734      42000.0
6552      15900.0
18166    114750.0
18906     33830.0
26268     13200.0
20416     13800.0
26221     32500.0
Name: price_x, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, cars_predictions)
rmse = np.sqrt(mse)

print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 14684.31023521308

In [ ]:
df_copy.to_csv('Turboaz_cleaned.csv', index=False)